;(function () {
    window.router = new VueRouter ({
        //全局配置router-link的css样式
        linkActiveClass:'active',
        //路由表
        routes:[
            {
                path:'/',//代表AppHome/
                component:AppHome
            },
            {
                path:'/news',
                component:News,
                children:[
                    {
                        //当匹配到/news/sport时，组件Sport会被渲染到news里面的<router-view></router-view>中
                        path:'/news/sport',
                        component:Sport,
                        children:[{
                            path:'/news/sport/detail/:id',//:id是路径变量，占位符
                            component:SportDetail
                        }]
                    },
                    {
                        //简写方式，相当于/news/Tech路径，注意前面不要有/，有/就是根路径了
                        path:'Tech',
                        component:Tech,
                        children:[
                            {
                                path:'/news/tech/detail/:id',
                                component:TechDetail
                            }
                        ]
                    },
                    {
                        //默认选择的路由：相当于/news,后面没有子路径redirect就是重写向指定的路径，及体育
                        path:'',
                        redirect:'/news/sport'
                    }
                ]
            },
            {
                path:'/about',
                component:About
            }
        ]
    })
})()